allowBuilds:
  cpu-features: set this to true or false
  glibc-version: set this to true or false
  kerberos: set this to true or false
  mongodb-client-encryption: set this to true or false
  mongodb-crypt-library-version: set this to true or false
  native-machine-id: set this to true or false
  os-dns-native: set this to true or false
  ssh2: set this to true or false
